export const matchingNakshatraList = [
  { english: "Revathi", tamil: "ரேவதி", score: 10 },
  { english: "Uthirattathi", tamil: "உத்திரட்டாதி", score: 8 },
  { english: "Bharani", tamil: "பரணி", score: 8 },
  { english: "Poosam", tamil: "பூசம்", score: 8 },
  { english: "Thiruvonam", tamil: "திருவோணம்", score: 8 },
  { english: "Chathayam", tamil: "சதயம்", score: 8 },
  { english: "Thiruvathirai", tamil: "திருவாதிரை", score: 8 },
  { english: "Aswini", tamil: "அசுவினி", score: 7 },
  { english: "Rohini", tamil: "ரோகிணி", score: 7 },
  { english: "Mirugasheerisham", tamil: "மிருகசீரிடம்", score: 7 },
  { english: "Swathi", tamil: "சுவாதி", score: 7 },
  { english: "Pooram", tamil: "பூரம்", score: 6 },
  { english: "Hastham", tamil: "அஸ்தம்", score: 6 },
  { english: "Kettai", tamil: "கேட்டை", score: 6 },
  { english: "Pooraadam", tamil: "பூராடம்", score: 6 },
  { english: "Anusham", tamil: "அனுஷம்", score: 5 },
  { english: "Makam", tamil: "மகம்", score: 4 },
] as const;

export const StateList = ["Tamil Nadu", "Kerala", "Karnataka"] as const;

export const DistrictList = {
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thiruvallur",
    "Thiruvarur",
    "Thiruvannamalai",
    "Thoothukudi (Tuticorin)",
    "Tiruchirappalli (Trichy)",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  Karnataka: [
    "Bagalkot",
    "Ballari (Bellary)",
    "Belagavi (Belgaum)",
    "Bengaluru Rural",
    "Bengaluru Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikkamagaluru (Chikmagalur)",
    "Chitradurga",
    "Dakshina Kannada",
    "Davanagere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalaburagi (Gulbarga)",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysuru (Mysore)",
    "Raichur",
    "Ramanagara",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Udupi",
    "Uttara Kannada (Karwar)",
    "Vijayapura (Bijapur)",
    "Yadgir",
  ],
} as const;
